#!/bin/sh -
cat <<'EOF'
# dmidecode 3.1
Getting SMBIOS data from sysfs.
SMBIOS 2.7 present.
5 structures occupying 233 bytes.
Table at 0x7F780000.

Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
	Vendor: Amazon EC2
	Version: 1.0
	Release Date: 12/1/2018
	Address: 0xF0000
	Runtime Size: 64 kB
	ROM Size: 64 kB
	Characteristics:
		PCI is supported
		EDD is supported
		ACPI is supported
		System is a virtual machine
	BIOS Revision: 1.0

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: Amazon EC2
	Product Name: a1.medium
	Version: Not Specified
	Serial Number: ec2ce86a-12c2-9388-d9b0-8dc833cba752
	UUID: ec2ce86a-12c2-9388-d9b0-8dc833cba752
	Wake-up Type: Power Switch
	SKU Number: Not Specified
	Family: Not Specified

Handle 0x0002, DMI type 2, 15 bytes
Base Board Information
	Manufacturer: Amazon EC2
	Product Name: Not Specified
	Version: Not Specified
	Serial Number: Not Specified
	Asset Tag: i-01c1b85d3dcc02ed7
	Features: None
	Location In Chassis: Not Specified
	Chassis Handle: 0x0003
	Type: Other
	Contained Object Handles: 0

Handle 0x0003, DMI type 3, 21 bytes
Chassis Information
	Manufacturer: Amazon EC2
	Type: Other
	Lock: Not Present
	Version: Not Specified
	Serial Number: Not Specified
	Asset Tag: Amazon EC2
	Boot-up State: Safe
	Power Supply State: Safe
	Thermal State: Safe
	Security Status: None
	OEM Information: 0x00000000
	Height: Unspecified
	Number Of Power Cords: 1
	Contained Elements: 0

Handle 0xFEFF, DMI type 127, 4 bytes
End Of Table

EOF
